spring:
  profiles:
    active:
    - dev
---

server:
  port: 8081

eureka:
  client:
#    register-with-eureka: false
    service-url:
      defaultZone: http://eureka-a:7001/eureka/,http://eureka-b:7002/eureka/,http://eureka-c:7003/eureka/

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"